---
name: k8s-dev Tool

'on':
  push:

  pull_request:

jobs:
  build:
    name: Build Tool
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: ${{ github.workspace }}/go.sum
          go-version-file: ${{ github.workspace }}/go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          args: build --snapshot --clean
          distribution: goreleaser
          version: '~> v2'

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Release Tool
    needs: [build]
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: ${{ github.workspace }}/go.sum
          go-version-file: ${{ github.workspace }}/go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          args: release
          distribution: goreleaser
          version: '~> v2'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
